name: "Sync"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          rm -rf .temp
          git clone -q --single-branch --depth=1 --branch=master https://github.com/hassio-addons/repository.git .temp
          
      - name: Create local changes
        run: |
          rm -rf .temp/.git
          rm -rf .temp/.github
          rm -rf .temp/.devcontainer
          rm -rf .temp/.vscode

          declare -a slug_image
          for d in .temp/* ; do
              if [ -f "$d/config.yaml" ]; then
                name=$(cat $d/config.yaml | grep -Po '(^name:).*' | sed 's/name://g' | sed 's/^[ \t]*//g' | sed 's/"//g')
                version=$(cat $d/config.yaml | grep -Po '(^version:).*' | sed 's/version://g' | sed 's/^[ \t]*//g' | sed 's/"//g')
                slug=$(cat $d/config.yaml | grep -Po '(^slug:).*' | sed 's/slug://g' | sed 's/^[ \t]*//g' | sed 's/"//g')
                image=$(cat $d/config.yaml | grep -Po '(^image:).*' | sed 's/image://g' | sed 's/^[ \t]*//g' | sed 's/"//g')
                slug_image+=("{\"slug\": \"$slug\", \"image\": \"$image\", \"version\": \"$version\", \"name\": \"$name\"}")

                sed -i 's/image: ghcr.io/image: ghcr.dockerproxy.com/' $d/config.yaml
                sed -i 's/image: homeassistant/image: dockerproxy.com\/homeassistant/' $d/config.yaml
              fi
              if [ -f "$d/config.json" ]; then
                name=$(cat "$d/config.json" | jq -r ".name")
                version=$(cat "$d/config.json" | jq -r ".version")
                slug=$(cat "$d/config.json" | jq -r ".slug")
                image=$(cat "$d/config.json" | jq -r ".image")
                slug_image+=("{\"slug\": \"$slug\", \"image\": \"$image\", \"version\": \"$version\", \"name\": \"$name\"}")

                if [[ $image = ghcr.io* ]]; then
                  new_image=${image/ghcr.io/ghcr.dockerproxy.com}
                else
                  new_image="dockerproxy.com/$image"
                fi
                
                sed -i "s|$image|$new_image|g" $d/config.json

                cat $d/config.json
              fi
          done
          shopt -s extglob
          rm -rf !(.git|.temp)
          shopt -u extglob
          cp -r .temp/* ./
          rm -rf .temp

          S=$(IFS=,; echo "${slug_image[*]}")
          echo "[$S]" > addons.json
          echo '{"name":"Home Assistant Community Add-ons 代理加速","url":"https://addons.community","maintainer":"Franck Nijhof <frenck@addons.community>"}' > repository.json


      - name: Commit files
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Sync."

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
